services:
  # PostgreSQL Database
  db:
    image: postgres:18.0-alpine
    container_name: assistiq-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - "../.env"
    environment:
      - POSTGRES_DB=${DB_NAME:-assistiq}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin4
  pgadmin:
    image: dpage/pgadmin4:2025-10-14-1
    container_name: assistiq-pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - "../.env"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_LOGIN_BANNER="AssistIQ DB"
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      db:
        condition: "service_healthy"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: assistiq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - "../.env"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    healthcheck:
      test: ["CMD", "rabbitmq-diagonstics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:8.2.3
    container_name: assistiq-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: assistiq-api
    ports:
      - "8080:8000"
    volumes:
      - ../:/app
    env_file:
      - "../.env"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # Celery Worker:
  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: assistiq_celery_worker
    command: celery -A config worker -l info

    volumes:
      - ../:/app
    env_file:
      - "../.env"
    depends_on:
      - db
      - rabbitmq
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  rabbitmq_data:
